### ISSUE TITLE
block place sound

### ISSUE THREAD

**Issue by noy98** [Flenix/FlenixRoads#14]
Nobody cannot hear the sound when someone place Tan Sidewalk block.

**Comment by Fureniku** [comment]
I've not been able to reproduce this and no one else seems to be getting the problem. Also, due to how blocks work, there's no reason why this would be exclusive to tan sidewalks - if anything all sidewalks and probably all road blocks would have the issue as well.

If you are still having the problem, please try running the mod alone with no other mods installed and see if it still happens.
