### ISSUE TITLE
Massive, unplayable frame spikes

### ISSUE THREAD

**Issue by SodWhite** [Flenix/FlenixRoads#25]
I haven't used this mod since around 1.7.10 when it was still named FlenixRoads, but I never experienced _near_ this much frame loss as with 1.12.2. I haven't even gotten as far as placing roads yet; the frame spikes become worse as time goes on after simply joining a world until there is no noticeable gap between them. It goes from bad, to worse, to slideshow, to still image.

Using an RTX2070 and 32GB memory, and it's burning through all of it.

**Comment by Fureniku** [comment]
If you've not even placed a block yet I can't see how roads would be causing any in-game lag.

Can you please give me your full mod list?

**Comment by SodWhite** [comment]
My modlist is as follows. Mods listed are for build 1.12.2:

SecurityCraft 1.8.16
CFM 6.3.0
Chisel 0.2.1.35
CTM 0.3.3.22
Extra Utilities 1.9.9
Immersive Vehicles 17.3.1
Immersive Railroading 1.7.3
IndustrialCraft2 2.8.196
Industrial Renewal 0.16.1
Mekanism 9.8.3.390
MineTraps 1.0.4
MTS Heavy Industrial 1.9.1
Obfuscate 0.2.6
UNU Military Pack 17.0.0-3.3.1
UNU Parts Pack 17.0.0-3.3.1
TechGuns 2.0.1.1
TrackAPI 1.2
Vehicle mod 0.43.5
Fureniku's Roads 1.1.6

Just loading the Java client with this mod installed is very, very slow and throws the following error:

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniversalModCore (universalmodcore)

To try to narrow down a culprit I stepped the versions back as far as 1.0; the game still loads slow, but does not throw an error. Instead, the game performs at slideshow levels.

**Comment by Fureniku** [comment]
UniversalModCore is nothing to do with me - that's a requirement of Immersive Railroading/TrackAPI.

As for slow launching, that's pretty normal I'm afraid. Every mod you add will slow down the launch a little, and the more "stuff" that mod adds, the slower launch will be. However, the progress bars should still be progressing quickly, they just have more things to show - as long as all the loading text is flying past faster than you can read it it's not actually an issue, just a caveat of using a modpack.

Roads does take a little longer to load than something like a tech mod might, simply because it has a lot more blocks (all those paints have a lot of variants to make them connect together).

What launcher are you using, and have you set any launch arguments? By default the vanilla launcher will only use 1gb of RAM, other launchers might have different properties but I'd suggest making sure you have at least 4gb allocated (I personally use 8gb). I'd guess this is your most likely issue to be honest, as I use most of the mods in your list alongside quite a few others with Roads and while my pack launch is about five minutes, once I'm in game everything is fine.

**Comment by SodWhite** [comment]
Edit: Allocated 4GB. Error ceased, game loads normally. Thanks for the help.
