### ISSUE TITLE
Fureniku's Roads R 1.0  have 2bugs

### ISSUE THREAD

**Issue by Titoo8899** [Flenix/FlenixRoads#3]
Hi,
I have found 2 Bugs and have Pictures for you. I hope this Picture help you to fix the 2 Problems.
![2019-02-12_17 25 02](https://user-images.githubusercontent.com/42325138/52651132-ee32a700-2eeb-11e9-97dc-9c8a3419c47e.png)
![2019-02-12_17 25 10](https://user-images.githubusercontent.com/42325138/52651133-ee32a700-2eeb-11e9-9122-53dd736fe809.png)
![2019-02-12_17 25 35](https://user-images.githubusercontent.com/42325138/52651134-ee32a700-2eeb-11e9-983d-8572fc4c760c.png)
![2019-02-12_17 26 30](https://user-images.githubusercontent.com/42325138/52651135-ee32a700-2eeb-11e9-83cc-123921e2e4fb.png)

**Comment by Titoo8899** [comment]
The First 3 Picture have the Curb Place and see Problem. I have a invisible Bug found.
The last Picture have the Icon Bug from your Mod. The Grassblock have not Colour.

**Comment by Fureniku** [comment]
Thanks for taking the time to report these! Can you please try this build and let me know if they're both fixed?

Please note that grass blocks do not have dirt on the side like vanilla grass; this is intentional.

[Fureniku's Roads-1.0.1.zip](https://github.com/Fureniku/Furenikus-Roads/files/2857219/Fureniku.s.Roads-1.0.1.zip)

**Comment by Titoo8899** [comment]
You can close this it is fix all the bugs
