### ISSUE TITLE
Road block apears Transparent with fake light

### ISSUE THREAD

**Issue by stiderspace** [Flenix/FlenixRoads#36]
Road blocks appear transparent when a fake light block is placed on top of them. 

![Screenshot_1](https://user-images.githubusercontent.com/4059700/106896908-7c645100-66f2-11eb-8bc8-0ef44486a602.png)

**Comment by jcc10** [comment]
This also effects *a **lot*** of other mod's street lights. I would guess that it has something to do with the alpha getting borked due to the fact that the block can be at multiple heights. This does happen with concrete blocks, but not the solid ones, only the ones that can "slope"

Interim fixes: Place curb blocks below street lamps on the road. This causes the fake light to be on the curb block. Alternatively, place a drain below the lamp. ~~(not sure if paint fixes it. It might but I can't be bothered to load up my mod-pack to find out.)~~ Or paint.

**Comment by Fureniku** [comment]
I'm aware of the problem and it's a simple fix that I'll release as soon as I have time, I'm in the middle of deadline season at the moment unfortunately so it'll be another week or so. In the mean time jcc10's workarounds will work, or you can revert to an earlier release, or just live with the problem (they'll all be automatically fixed by the patch)

**Comment by jcc10** [comment]
@Fureniku I would like to ask if this is the same bug as the one that causes the ground to go invisible or if it is a different one. Asking mostly so I know if I need to build around it or just ignore the visual issues for now.

![2021-02-13_12 02 38](https://user-images.githubusercontent.com/1398636/107860296-7279d680-6df3-11eb-8b36-cba545024c04.png)

**Comment by Fureniku** [comment]
There's a fix for this in 1.2 which will work with any of _my_ blocks. I've added a catch for other mods which haven't implemented their blocks properly too, but if you still experience any culling issues after 1.2 please let me know which blocks they're happening with. (There's always a chance I've missed some of my own, this mod has a lot of blocks!) 

I'll leave the issue open until 1.2's first beta releases which is still a few weeks away at best, but if you're super keen to test it poke me on Discord and I can give you an alpha version (not world-safe so only use on test worlds!)

**Comment by Fureniku** [comment]
1.2 beta has been out for a few weeks now and no further comment on the issue has been seen
