### ISSUE TITLE
Machine energy does not update when near full.

### ISSUE THREAD

**Issue by Xavienth** [Flenix/FlenixRoads#43]
I've only tested this on the paint oven. It seems to be a visual bug, as all the energy is added at once when updated.
1. Connect paint oven to power source.
2. Disconnect when it has 46,000 RF or higher (not sure of this number, 45,500 also reproduced)
3. Reconnect
4. Paint oven no longer accepts power until the machine is updated in some way, as in a dye is processed, water is added, etc.

**Comment by Fureniku** [comment]
This is basically due to how I handle the update packets to the client. The server always has the correct energy value, but only sends this info to the client alongside other info (for example, any of the updates you list).
I could send the updates more frequently, but this would then use more network traffic. It's very negligible, but I opted for this over what would effectively be useless network traffic.

That being said I'll look into having a clientside check for if the machine and the nearby power source are both full, then it can just mark itself as "full" until an update says otherwise. I'll look into this a bit closer to 1.2 release as it's pretty low priority
